[package]
name = "krabka-cli"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Operator CLI for Krabka (binary: `krabka`)"
repository = "https://github.com/krabka-io/krabka-cli"
homepage = "https://github.com/krabka-io/krabka-cli"
documentation = "https://docs.rs/krabka-cli"
readme = "README.md"
keywords = ["kafka", "cli", "operator", "krabka"]
categories = ["command-line-utilities"]

[[bin]]
name = "krabka"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
assert2 = { workspace = true }
clap = { workspace = true, features = ["env"] }
krabka-security = { workspace = true }
krabka-client-core = { version = "0.4.0" }
krabka-client-admin = { version = "0.4.0" }
krabka-units = { workspace = true }
krabka-metadata = { version = "0.4.0" }
krabka-raft = { version = "0.4.0" }
derive_more = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs"] }
serde-wincode = { workspace = true }
wincode = { workspace = true }
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
krabka-broker = { version = "0.4.0" }
tempfile = { workspace = true }
